version: '3'

services:
  app:
    image: traefik:2.6.3
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Africa/Lome
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./traefik_dynamic.yml:/traefik_dynamic.yml
      - ./acme.json:/acme.json
    restart: always

networks:
  default:
    external:
      name: traefik-proxy
