################################################################
# Http
################################################################

http:
  middlewares:
    traefik-dashboard-auth:
      basicAuth:
        users:
          - "admin:1RAxezGFfvn@"

  routers:
    traefik-dashboard:
      rule: "Host(`traefik.longbowou.com`)"
      entrypoints:
        - http
      service: "api@internal"
      tls:
        certResolver: le
