################################################################
# Http
################################################################

http:
  middlewares:
    traefik-dashboard-auth:
      basicAuth:
        users:
          - "admin:1RAxezGFfvn@"

  routers:
    traefik-dashboard:
      rule: "Host(`traefik.longbowou.com`)"
      middlewares:
        - traefik-dashboard-auth
      entrypoints:
        - https
      service: "api@internal"
      tls:
        certResolver: le
